# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 14:16
from __future__ import unicode_literals

import article.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('article_date', models.DateTimeField(verbose_name='Дата публикации статьи')),
                ('article_likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('article_author', models.CharField(blank=True, max_length=200, verbose_name='Автор статьи')),
                ('short_text_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Короткое описание RU')),
                ('short_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Короткое описание EN')),
                ('video', models.CharField(blank=True, max_length=250, verbose_name='Видео id в кратком описании')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=article.models.make_upload_path, verbose_name='Изображение')),
                ('full_text_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Полное описание RU')),
                ('full_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Полное описание EN')),
                ('article_video', embed_video.fields.EmbedVideoField(help_text='описание видео', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25, verbose_name='Название категории транслитом')),
                ('category_title', models.CharField(blank=True, max_length=25, null=True, verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('comments_text', models.TextField(verbose_name='Добавте Ваш комментарий')),
                ('comments_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='Статья')),
                ('comments_user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=25, verbose_name='Название тега транслитом')),
                ('tag_title', models.CharField(max_length=25, verbose_name='Имя тега')),
            ],
            options={
                'verbose_name': 'тега',
                'verbose_name_plural': 'тег',
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(related_name='articles', to='article.Tag', verbose_name='Теги'),
        ),
    ]
