# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import embed_video.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, unique=True, verbose_name='Автор статьи')),
                ('author_title', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Автор статьи транслитом')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.Author', verbose_name='Родительский класс')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'authors',
                'ordering': ('tree_id', 'level'),
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('tree_id', 'level'), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25, null=True, unique=True, verbose_name='Название категории транслитом'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.Category', verbose_name='Родительский класс'),
        ),
        migrations.AddField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=mptt.fields.TreeForeignKey(blank=True, default='', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='article.Author', verbose_name='Автор статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=mptt.fields.TreeForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='описание видео', null=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Имя категории'),
        ),
    ]
