# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160519_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Автор статьи транслитом'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Имя категории'),
        ),
    ]
