# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20160519_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='parent',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Автор статьи'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
