# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160519_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='Автор статьи')),
                ('author_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Автор статьи транслитом')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.Author', verbose_name='Родительский класс')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
                'verbose_name': 'Автор',
                'db_table': 'authors',
                'ordering': ('tree_id', 'level'),
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=mptt.fields.TreeForeignKey(blank=True, default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='article.Author', verbose_name='Автор статьи'),
        ),
    ]
