# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160521_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Автор статьи'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='Автор статьи транслитом'),
        ),
    ]
