# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20160521_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'теги', 'verbose_name_plural': 'тег'},
        ),
        migrations.AlterField(
            model_name='author',
            name='author_title',
            field=models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='Автор статьи'),
        ),
    ]
