# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20160522_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(related_name='tags', related_query_name='tags', to='article.Tag', verbose_name='Теги'),
        ),
    ]
