# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20160524_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Название категории транслитом'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=50, verbose_name='Название тега транслитом'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(max_length=50, verbose_name='Имя тега'),
        ),
    ]
