# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20160524_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_published',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='video_published',
            field=models.BooleanField(default=''),
        ),
    ]
