# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20160601_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='number_articlies',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество статей в курсе'),
        ),
    ]
