# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20160612_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_number',
        ),
        migrations.RemoveField(
            model_name='category',
            name='number_articlies',
        ),
    ]
