# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20160628_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments_article',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comments_user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
