# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20160628_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Урл'),
        ),
    ]
