# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20160827_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_likes',
        ),
    ]
