# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_remove_article_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_title',
        ),
    ]
