# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_remove_tag_tag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_title',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='Автор статьи'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=50, verbose_name='Название тега'),
        ),
    ]
