# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_auto_20160928_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_title',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, unique=True, verbose_name='Имя категории'),
        ),
    ]
